# API配置文件

# 搜索引擎配置（使用 SerpAPI 代理的 Google 搜索）
serpapi_google:
  enabled: true
  api_key: "08d8f958b2f102865798a4c28480f8506376f7fe91be7ddc00dcfed8404485cf"
  # 参考 https://serpapi.com/google-search-api
  google_domain: "google.com"
  gl: "us"         # 地理位置 (e.g., cn, us)
  hl: "zh-cn"      # 界面语言
  num: 10           # 每页结果数
  max_results: 30   # 最大采集数

# NewsAPI配置
newsapi:
  enabled: true
  api_key: "7ef303e7bb7641ee9b7a8050cc23f309"
  endpoint: "https://newsapi.org/v2/everything"

# arxiv API配置 - arXiv OAI-PMH v2.0(获取学术性和专业性更强的数据)
arxiv:
  enabled: true
  # OAI-PMH 基础 URL（2025年3月更新）
  endpoint: "https://oaipmh.arxiv.org/oai"
  # 元数据格式: oai_dc, arXiv, arXivRaw
  metadata_format: "arXiv"
  # 默认采集的分类集合 (set)
  # 格式: group:archive:CATEGORY
  # 例如: cs (all CS), cs:cs:AI (AI only), physics:hep-th
  default_sets:
    - "cs"  # computer science
  # 每次请求的最大记录数
  max_records: 30

# 大模型API配置 (可选择Qwen, gemini等)
llm:
  provider: "qwen"  # qwen, gemini, llama(optional)
  api_key: "sk-312d7a8ba0034510b93e96246956bc00"
  model: "qwen3-max"
  endpoint: "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation"
  max_tokens: 2000
  temperature: 0.7

# 图像生成API配置（可选）
image_generation:
  enabled: false
  provider: "dalle"  # dalle, stable-diffusion
  api_key: "YOUR_IMAGE_API_KEY"
